import { PERMISSIONS } from "./permissions.config";

export const GROUP_PERMISSIONS = {
  "SA-TICKETS-RESOLUTOR": [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_TICKETS,
    PERMISSIONS.TICKETS_CHANGE,
    PERMISSIONS.CREATE_TICKETS,
    PERMISSIONS.CREATE_TEMPLATE,
  ],
  "SA-TICKETS-ADMINISTRADOR": [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ALL_TICKETS,
    PERMISSIONS.CREATE_TICKETS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.CREATE_TEMPLATE,
    PERMISSIONS.TICKETS_CHANGE

  ],
  "SA-TICKETS-USUARIOS": [
    PERMISSIONS.VIEW_TICKETS,
    PERMISSIONS.CREATE_TICKETS,
  ],
} as const;