import { PERMISSIONS } from "./permissions.config";

export const GROUP_PERMISSIONS = {
  "SA-TICKETS-RESOLUTOR": [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_TICKETS,
    PERMISSIONS.TICKETS_CHANGE,
    PERMISSIONS.CREATE_TICKETS,
    PERMISSIONS.CREATE_TEMPLATE,
    PERMISSIONS.VIEW_EXCEL,
    PERMISSIONS.BULK_CREATE_TICKETS,
    PERMISSIONS.APPROVE_TICKETS
  ],
  "SA-TICKETS-ADMINISTRADOR": [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ALL_TICKETS,
    PERMISSIONS.CREATE_TICKETS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.CREATE_TEMPLATE,
    PERMISSIONS.TICKETS_CHANGE,
    PERMISSIONS.VIEW_EXCEL,
    PERMISSIONS.BULK_CREATE_TICKETS,
    PERMISSIONS.APPROVE_TICKETS

  ],
  "SA-TICKETS-USUARIOS": [
    PERMISSIONS.VIEW_TICKETS,
    PERMISSIONS.CREATE_TICKETS,
  ],
  "SA-TICKETS-OBSERVADORES": [
    PERMISSIONS.VIEW_ALL_TICKETS,
  ],
  "SA-TICKETS-JEFES-ZONA": [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ALL_TICKETS,
    PERMISSIONS.CREATE_TICKETS,
    PERMISSIONS.APPROVE_TICKETS,
  ],
} as const;